language: c
sudo: false # only for faster builds
compiler: 
 - clang
 - gcc
script:
 - gcc -o risingedgefallingedge risingedgefallingedge.c // we can use gcc instead of clang too
 - ./risingedgefallingedge
